- name: Install HAProxy
  dnf:
    name: haproxy
    state: latest

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Ensure HAProxy is enabled and running
  systemd:
    name: haproxy
    enabled: yes
    state: restarted