---
- name: Disable SELinux
  selinux:
    state: disabled
    
- name: Disable firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stopped

- name: Allow nonlocal bind
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
    reload: yes

- name: Set SELinux to permissive mode
  command: setenforce 0
  ignore_errors: yes  # 이 작업이 실패해도 나머지 작업을 계속 진행
  changed_when: false # 이 명령은 상태 변경을 확인하지 않으므로 항상 'changed' 상태를 반환하지 않음

- name: Check SELinux status
  command: getenforce
  register: selinux_status

- name: Output current SELinux status
  debug:
    msg: "Current SELinux status is {{ selinux_status.stdout }}"

